name: nutrisnap
description: A flutter app to encourage healthy eating habits.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.9.2
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  firebase_storage: ^11.2.7
  firebase_ui_auth: ^1.8.0
  fl_chart: ^0.63.0
  flutter_svg: ^2.0.7
  foundation: ^0.0.5
  google_sign_in: ^6.1.5
  http: ^1.1.0
  sign_in_with_apple: ^5.0.0
  hooks_riverpod: ^2.4.3
  shared_preferences: ^2.2.1
  flutter_hooks: ^0.20.2
  riverpod_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.1
  custom_lint: ^0.5.3

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/food/
    - assets/images/layout/
    - assets/svgs/
    - assets/images/layout/foodplaceholder.png
