// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUE-E-nE7yFDGDeBOO9C38JMu5C5ruJiY',
    appId: '1:468414971628:web:4fe26b6256e9f1761cefc9',
    messagingSenderId: '468414971628',
    projectId: 'nutrisnap-ai',
    authDomain: 'nutrisnap-ai.firebaseapp.com',
    storageBucket: 'nutrisnap-ai.appspot.com',
    measurementId: 'G-HFTKF58DJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGgrC8clRBnhAACjlzfv_Aq-ucbLJ8MLo',
    appId: '1:468414971628:android:9cfa5eb89e4c764f1cefc9',
    messagingSenderId: '468414971628',
    projectId: 'nutrisnap-ai',
    storageBucket: 'nutrisnap-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVBLQ5vAf07zzOF72NZLjX_2cqMwwVAjM',
    appId: '1:468414971628:ios:031bef950895a5ea1cefc9',
    messagingSenderId: '468414971628',
    projectId: 'nutrisnap-ai',
    storageBucket: 'nutrisnap-ai.appspot.com',
    iosClientId: '468414971628-2mc425c2oaauife2gfa824k2q537feru.apps.googleusercontent.com',
    iosBundleId: 'com.example.nutrisnap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVBLQ5vAf07zzOF72NZLjX_2cqMwwVAjM',
    appId: '1:468414971628:ios:b9391e0f662b6dca1cefc9',
    messagingSenderId: '468414971628',
    projectId: 'nutrisnap-ai',
    storageBucket: 'nutrisnap-ai.appspot.com',
    iosClientId: '468414971628-174p2g3ulpgu5ctjqh8ad1uvlqg1kq48.apps.googleusercontent.com',
    iosBundleId: 'com.example.nutrisnap.RunnerTests',
  );
}
